# Generated by Django 4.1.6 on 2023-10-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Ангиллын нэр"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Тайлбар"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children",
                        to="main_app.category",
                        verbose_name="Эцэг ангилал",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ангилал",
            },
        ),
    ]
