# Generated by Django 4.1.6 on 2023-10-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=100, verbose_name="Гарчиг"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Мэдээний агуулга"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="main_app.category",
                        verbose_name="Ангилал",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Мэдээ",
            },
        ),
    ]
