# Generated by Django 4.1.6 on 2023-10-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_artice"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artice",
            new_name="Article",
        ),
    ]
